export interface RelatedBook {
  title: string;
  author: string;
  affiliateUrl: string;
  coverHint?: string;
}

export interface VideoTimestamp {
  youtubeId: string;       // e.g. "dQw4w9WgXcQ"
  startSeconds: number;    // seek to this time
  endSeconds?: number;
  speakerName?: string;    // who said it in the video
  thumbnailUrl?: string;
}

export type SourceType =
  | "book"
  | "movie"
  | "speech"
  | "essay"
  | "article"
  | "interview"
  | "poem"
  | "tweet"
  | "wikiquote"
  | "unknown";

export interface Quote {
  id: string;
  slug: string;
  text: string;
  author: string;
  source?: string;
  year?: number;
  category: string;
  context?: string;
  tags: string[];
  likes: number;
  bookmarks: number;
  sourceType?: SourceType;
  relatedBooks?: RelatedBook[];
  // Video quote fields
  videoTimestamp?: VideoTimestamp;
  // Submission metadata
  submittedBy?: string;    // userId or "admin"
  submittedAt?: string;    // ISO date string
  status?: "published" | "pending" | "rejected";
  // Revenue
  sponsored?: boolean;
  sponsorLabel?: string;
  sponsorUrl?: string;
}

export interface Comment {
  id: string;
  username: string;
  avatar: string;
  text: string;
  createdAt: string;
  userId?: string;
  isCounterpoint?: boolean;
  isAdmin?: boolean;
}

export interface DiscussionStore {
  quoteId: string;
  comments: Comment[];
  aiCounterpoint?: string;
}

export interface CustomCollection {
  id: string;
  name: string;
  description?: string;
  quoteIds: string[];
}

// ── User ─────────────────────────────────────────────────────────────────────
export interface User {
  id: string;
  name: string;             // display name (or "Anonymous")
  handle: string;           // e.g. "socrates_21"
  email: string;
  avatar: string;
  bio?: string;
  anonymous?: boolean;      // hides real name/avatar publicly
  role: "user" | "moderator" | "admin";
  joinedAt: string;
  savedQuoteIds: string[];
  submittedQuoteIds: string[];
  isSubscribed: boolean;    // newsletter
  emailVerified?: boolean;  // email address confirmed via verification link
  interests: string[];      // topic tags for personalised newsletter
}

// ── Auth API payloads ─────────────────────────────────────────────────────────
export interface AuthResponse {
  token: string;
  user: User;
}

export interface RegisterPayload {
  displayName: string;
  email: string;
  password: string;
  interests: string[];
  turnstileToken?: string;
}

export interface Subscriber {
  id: string;
  email: string;
  name: string;
  subscribedAt: string;
  unsubscribedAt: string | null;
  status: "subscribed" | "unsubscribed" | "spam";
  source: "homepage" | "quote_page" | "admin" | "footer";
}

// ── Author ────────────────────────────────────────────────────────────────────
export interface AuthorProfile {
  id: string;
  slug: string;
  name: string;
  fullName?: string;
  bio: string;
  imageUrl?: string;
  born?: string;
  died?: string;
  nationality?: string;
  knownFor?: string;
  autoGenerated?: boolean;
  enrichedAt?: string;
  quoteCount?: number;
}

// ── YouTube extraction result (from Gemini) ───────────────────────────────────
export interface ExtractedQuote {
  text: string;
  speaker: string;
  startSeconds: number;
  endSeconds: number;
  context: string;
  suggestedTags: string[];
  youtubeId: string;
}
